# Formularios y HTTP (ya vienen con Angular, solo debes importarlos)
npm install @angular/forms @angular/common

# ng-bootstrap (carousel, rating, etc.)
ng add @ng-bootstrap/ng-bootstrap

# Google Maps
ng add @angular/google-maps

# Angular Material (incluye datepicker, modales, tablas, etc.)
ng add @angular/material

# Opcional si usas Cloudinary desde Angular
npm install @cloudinary/url-gen @cloudinary/angular

# SweetAlert2 (alertas bonitas)
npm install sweetalert2
