# Base
npm install express cors dotenv

# ORM con TypeScript
npm install typeorm reflect-metadata

# Autenticación con JWT
npm install jsonwebtoken

# Cloudinary SDK
npm install cloudinary

# Para manejo de archivos (si recibes uploads desde Angular antes de Cloudinary)
npm install multer

# Seguridad y utilidades
npm install bcrypt helmet morgan

# Validaciones (si usas DTOs con TypeORM)
npm install class-validator class-transformer
