
npm install express cors dotenv


npm install typeorm reflect-metadata


npm install jsonwebtoken


npm install cloudinary


npm install multer


npm install bcrypt helmet morgan


npm install class-validator class-transformer
